#!/bin/sh
#
# An example hook script that is called after a successful
# commit is made.
#
# To enable this hook, make this file executable.
 
emacs --batch --eval '
  (htmlize-file (concat (pwd) "color-theme-tango-2.el") (concat (pwd) "web/"))'
cd web/
git ci -am "Pages: re-render html."
git push
    